services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    image: anton4ez/finance_bot:v1
    restart: always
    env_file:
      - .env
    environment:
      - MPLBACKEND=Agg
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata: